### ISSUE TITLE
'ascii' codec can't decode byte 0xd1 

### ISSUE THREAD

**Issue by lixuezhi001** [selik/xport#101]
when i open xpt files ,The program  occur this problem

label=tokens[5].strip(b'\x00').decode(TEXT_METADATA_ENCODING).rstrip(),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 0: ordinal not in range(128)
i use python3.9.0
please help me，thanks！

**Comment by caov2021** [comment]
It should be a encoding issue because this package use default encodings to extract the character .
![image](https://user-images.githubusercontent.com/80733498/223952161-7edb3799-170e-47c1-b254-21d093a67af8.png)

You can try the code below and set the encoding which your data used
```python
import xport.v56
from xport.v56 import _encoding

with _encoding(data="utf-8", metadata="utf-8"):
    with open('adae.xpt', 'rb') as f:
        library = xport.v56.load(f)
```

**Comment by selik** [comment]
@caov2021 Thanks for helping!

**Comment by selik** [comment]
Answered.
