### ISSUE TITLE
External call? XPORT V5?

### ISSUE THREAD

**Issue by postb99** [selik/xport#11]
Hello,

I have two questions:
1. How can I manage to call the script, to create a .xpt file with my data, from command line with all required data, since I work in a C# environment. I think I can call the python executable/script with properly formatted arguments, but what about arguments length? I also need to look up how to retrieve the program output (using Windows). Maybe can the documentation be improved for Python-newbies like me?

2. Is the produced .xpt file XPORT version 5 compliant? I'm required to produce such files, not version 6.

Thank you a lot.

**Comment by selik** [comment]
@postb99 The command-line interface is rudimentary and only reads XPT files. I can add the feature to write XPT files as well.

Have you installed Python?

I don't know if there's a difference between XPT files for SAS 5 vs SAS 6. Do you have any example files you can share?

**Comment by postb99** [comment]
Hello,

Thank you for your reply. I finally chose to implement my own xpt writer in C#. I saw that I have to write version 5 headers while your tool writes version 6 files. Reading your program's code helps. Thank you for your work.

**Comment by selik** [comment]
If you have a copy of SAS 5, you can probably use it to read CSVs and write XPTs. If you don't have a copy of SAS 5, how will you test to ensure your XPT-writer is correct?

**Comment by postb99** [comment]
I don't have a SAS copy. I intend to use Pinnacle 21 open-source validator. it's even useful to lazily create the define.xml file from a set of xpt files (generate the Excel spec from the files then the xml definition file).

For any C# people reading this, I found an interesting IEEE to IBM mainframe number converter here : https://www.codeproject.com/Articles/492449/Transform-between-IEEE-IBM-or-VAX-floating-point

**Comment by selik** [comment]
Ok, cool. If you decide you want a Python CLI instead, let me know. Best of luck!
