### ISSUE TITLE
Sas Dataset name 

### ISSUE THREAD

**Issue by cvpeceee** [selik/xport#16]
currently while writing a xpt file from dataframe, the from_columns function is called and here we write the member header records and default the name of the date set to b'dataset, see below code for reference
    # Member header data
    fp.write(b'SAS'
             b'dataset' # dataset name -customize this field
             b'SASDATA'
             + sas_version
             + os_version
             + 24 * b' '
             + created)
Can you help me to make the dataset name customizable or is there already a function for doing this? As we don't want the all datasets to have the same same as dataset

**Comment by selik** [comment]
I'm in the middle of revising the API, so this is a good time to request changes. What would be your ideal example for how to write an XPT-format file?

**Comment by selik** [comment]
Solved #34
