### ISSUE TITLE
ImportError: cannot import name reading

### ISSUE THREAD

**Issue by sbjain** [selik/xport#20]
ImportError: cannot import name reading

get this error when adding in the code as below:

with open('nsIQTScriptablePlugin.xpt', 'r') as f:
    for row in xport.Reader(f):
        print row

**Comment by selik** [comment]
Can you share the complete traceback?

**Comment by sbjain** [comment]
Traceback (most recent call last):

  File "ex1.py", line 18, in <module>

    import xport

  File "/Users/sagarjain/Desktop/xport/__init__.py", line 11, in <module>

    import reading

ImportError: No module named reading

Sagars-MBP-2:Desktop sagarjain$

**Comment by selik** [comment]
Looks like I've somehow left the master branch in a buggy state. How did you install the library? From PyPI?

**Comment by selik** [comment]
Try this version instead: https://pypi.org/project/xport/

The one from GitHub is under development. It looks like I didn't update the import statements after renaming some modules.

**Comment by sbjain** [comment]
Hi Michael,

Thanks I will check this new link shared for using xport package.

Also I wanted to check with your perspective, can the following be performed using xport package?:

Point to an initial location and open a study folder for an XPT dataset (a chronic one that you already have)
Search for and open each file and then edit the such that the study number is unique  - first time script runs, the study is renamed to 2018-001 and all animals and domain fields where study is referenced, the study number is changed to 2018-001.
Save the new dataset to a new folder in the location being monitored by Savante so that it may be ingested automatically.
Repeat steps 1,2 and 3 for 100 times

**Comment by selik** [comment]
This module will help you read and write XPT files. The other tasks will require other aspects of Python programming, but it sounds relatively straightforward.

**Comment by sbjain** [comment]
Ok thanks for your feedback. Yes the read and write components for xpt files will use xport package in that case. 

Can I use package to read a certain (data field) variable and edit its value? 
Please share syntax of how this would look, this will be very helpful. 

Thanks,
Sagar

**Comment by sbjain** [comment]
I am not much familiar unfortunately. Any link you recommend I review? Many thanks!

**Comment by sbjain** [comment]
Hi Michael,

I am getting ImportError: no named xport found.

Is this the correct way to configure the PyPI version?
1. Delete remove the github clone xport files
2. Download the tar zip file for xport PyPI -- saved code and package to
Desktop (same location).

Please advise.

Thanks,
Sagar

**Comment by selik** [comment]
`pip install xport`
I suggest you read a Python tutorial. There are many free classes online.

**Comment by sbjain** [comment]
Hi, is this the same command we use in windows Cygwin?

Has the github repo been updated to pull from there or still use PyPI?
Thanks

**Comment by selik** [comment]
I'm not familiar with Cygwin, but I think it'd be the same. I haven't made any updates to this repository in a while. I'll probably get around to it in a few months. Maybe this summer.

**Comment by sbjain** [comment]
Would be great help if you can guide how to read 1 column, write over it, then save it. New to csv and xpt. Thanks a lot!

**Comment by selik** [comment]
It sounds like you're also new to Python. There are many good online courses you can access for free or cheap.

**Comment by sbjain** [comment]
Hi Michael,

Yes that is why I am requesting a bit of help to nudge in right
direction. Really appreciate it.

I have used to_columns function in code below, I get an error with
to_columns. Is there something I need to configure?

with open('bg.xpt', 'rb') as f:
  from itertools import islice
  read_file = xport.Reader(f)
  row = next(islice(read_file, None, None))
  columns = xport.to_columns(f)

print columns

**Comment by selik** [comment]
When asking a programming question, it's helpful to share your code, what you expected to happen, and the error you're getting. You might also ask on StackOverflow (https://stackoverflow.com/), which is a question/answer community.

**Comment by sbjain** [comment]
Hi Michael,

Yes I have shared my code below in previous email. Please take a look if you can help

**Comment by selik** [comment]
> and the error you're getting

What's the error message?

**Comment by sbjain** [comment]
Hi Michael,

Please see if you can help (error, expected and code below).

I am getting the following error: $ python xport_test.py
Traceback (most recent call last):
  File "xport_test.py", line 6, in <module>
    for row in xport.Reader(f):
  File "/usr/lib/python2.7/site-packages/xport.py", line 160, in __init__
    version, os, created, modified = self._read_header()
  File "/usr/lib/python2.7/site-packages/xport.py", line 197, in _read_header
    tokens = tuple(t.rstrip() for t in struct.unpack(fmt, raw))
struct.error: unpack requires a string argument of length 80


Expected to have the xport file rows displayed -- as it did before


Code used here: #read the xpt file now
with open('bg.xpt', 'rb') as f:
	for row in xport.Reader(f):
		print row

**Comment by selik** [comment]
Sorry it took so long. I've fixed the HEAD version on GitHub and uploaded the latest to PyPI.
