### ISSUE TITLE
Reverse conversion (CSV to XPT)

### ISSUE THREAD

**Issue by sbjain** [selik/xport#26]
We have command line: python -m xport dm_1.xpt > ex.csv (input = xpt, output = csv)

Is there a reverse function we can use (input = csv, output = xpt). Please advise on solution.

Thanks,
Sagar

**Comment by sbjain** [comment]
Hmm how would we do that? Could you send a link on how to implement this csv to xpt. Thanks, Sagar

**Comment by selik** [comment]
Sorry, @sbjain, I don't have time at the moment.

**Comment by meyergt** [comment]
Read the .csv into a dataframe:
```
df = pd.read_csv('file.csv')
```
Convert the dataframe to a list of dictionaries to then write to .xpt:
```
data = df.T.to_dict().values()
```
Write the list of dictionaries to .xpt:
```
with open('file.xpt', 'wb') as f:
    xport.from_rows(data, f)
```

**Comment by selik** [comment]
Now you can write it directly.
```
import pandas as pd
import xport.v56

df = pd.read_csv('example.csv')
with open('example.xpt', 'wb') as f:
    xport.v56.dump(df, f)
```
