### ISSUE TITLE
from_columns error

### ISSUE THREAD

**Issue by sbjain** [selik/xport#27]
Hi, when using from_columns function from xport, I get following error for a couple files. The other 15 work fine. Please advise why this error occurs?

"xport.py", line 666, in from_columns
column[ i ] = value.encode('ISO-8859-1')
UnicodeDecodeError: 'ascii' codec cant decode byte 0xa0 in position 11: ordinal not in range(128).

**Comment by selik** [comment]
Sounds like those files have non-ascii characters, perhaps some emoji. You can ignore or replace those characters when encoding.

**Comment by selik** [comment]
Please make a new issue if this is still troubling you.
