### ISSUE TITLE
Specific columns names and column labels.

### ISSUE THREAD

**Issue by meyergt** [selik/xport#28]
Currently, when writing to the xpt from_columns, the module creates column names from the labels.  It would be helpful for our submissions to the FDA to be able to specify both the column names and column labels.  

For example, the first column is the study identifier.  The required column name is "STUDYID" and the column label should be "Study Identifier".  When I pass "Study Identifier" as the column label using from_column, the column name "Study_Id" is created and is not acceptable to the FDA.

When writing from_rows, the column name remains what I had populated in the dataframe but there is apparently not a way to then add column labels.

Michael, Thank you for your excellent work on this project!

**Comment by selik** [comment]
@meyergt Implemented with #34

**Comment by selik** [comment]
Example in the README https://github.com/selik/xport#writing-xpt
