### ISSUE TITLE
how can we add format and label while writing xpt file

### ISSUE THREAD

**Issue by rifat-khanam** [selik/xport#29]
I want to add label and format in columns . is there any function for this?

**Comment by selik** [comment]
I can't remember at the moment. The most recent working version is available on PyPI. The GitHub master branch HEAD is malfunctioning.

**Comment by selik** [comment]
There is now #34 
```
In [1]: import xport

In [2]: import xport.v56

In [3]: ds = xport.Dataset({'A': ['hello']})

In [4]: ds['A'].format = '$CHAR10.'

In [5]: with open('example.xpt', 'wb') as f:
   ...:     xport.v56.dump(ds, f)
   ...:
```

**Comment by shainky1703** [comment]
and how can we add label ????

**Comment by selik** [comment]
@shainky1703 Does this section of the README help you? https://github.com/selik/xport#writing-xpt
