### ISSUE TITLE
Library doesn't support compressed XPORT files - Warning message

### ISSUE THREAD

**Issue by jischebeck** [selik/xport#3]
The library doesn't support compressed XPORT files.
I.e. files starting with 

       **COMPRESSED** **COMPRESSED** **COMPRESSED** **COMPRESSED** **COMPRESSED**". 

Example files can be fetched from https://www.ctti-clinicaltrials.org/aact-database.

Having support for these files would be great, but might be complicated to do, as the format specification is not available.

Can you add a error message, that the XPORT file is a compressed XPORT (CPORT) file, which is not supported by the library?

Thanks.

**Comment by Healthdroid** [comment]
@jischebeck did you ever find a workaround for this? I am hitting same issue.

**Comment by selik** [comment]
@jischebeck For some reason GitHub wasn't alerting me on new issues. I just noticed this. I'll add a better error message and investigate for how to decompress.

**Comment by selik** [comment]
The module now checks for the CPORT header and raises `NotImplementedError` with a decent explanation (aa350c07cf4666523e106d28b7441c8eb36096da). Thanks for pointing this out @jischebeck. I'd never heard of CPT files before.

If you find a spec for them somewhere, let me know and I'll implement a reader.
