### ISSUE TITLE
How can I convert my data(represents multiple sas data set) into a single xpt? 

### ISSUE THREAD

**Issue by sakibbuddy** [selik/xport#31]
Currently, I can convert my JSON data in a xpt format and when I convert it to SAS data set, it contains only single SAS data set(.sas7bdat format).

Is there any way I can convert a JSON data into xpt format with multiple SAS datasets(.sas7bdat format)?

Thanks in advance

**Comment by selik** [comment]
I'm not sure what you mean. This tool converts Python data structures into XPT format and vice versa. As a convenience feature, it can also write Python structures to CSV using the standard library `csv` module. This module does not interact with JSON, but you can use the standard library `json` module to read that data and use this module afterwards to write XPT format.

**Comment by selik** [comment]
@sakibbuddy I've added this feature in #34 .  The project supports libraries with multiple datasets.
