### ISSUE TITLE
cannot install using setup.py

### ISSUE THREAD

**Issue by rapIsKal** [selik/xport#32]
1. Clone repo
2. python setup.py install (under ven,  python 3.7)
Result
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    import xport
  File "/Users/gorelov/PycharmProjects/xport/xport/__init__.py", line 11, in <module>
    from . import reading
ImportError: cannot import name 'reading' from 'xport'

**Comment by selik** [comment]
Yeah, I accidentally pushed work in progress here. But the latest I uploaded to PyPI works.

**Comment by selik** [comment]
Fixed! Sorry it took me so long.

**Comment by selik** [comment]
`pip install --upgrade xport` to get the latest.
