### ISSUE TITLE
ParseError in _read_observations

### ISSUE THREAD

**Issue by michelleb098** [selik/xport#33]
I'm getting the following error parsing an xpt file - 
```
xport.py, line 188, in __iter__
    for obs in self._read_observations(self._variables):
xport.py, line 367, in _read_observations
    raise ParseError('incomplete record', sentinel, block)
data_integration.utilities.xport.ParseError: incomplete record -- expected b'  ', got b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
```
Note there are many spaces between the quotes in "expected b' ' " that I omitted. 

It looks like spaces are expected, but it's getting null characters instead. This is a SaS version 9.4 xpt file, but I've parsed many other version 9.4 files using this library without an issue. Also interestingly I can read the header/schema of this file using this library fine, I'm just having issues parsing the rows.

I don't think the file itself is corrupt, because it can be parsed correctly in R using haven::read_xpt. I'm using the most reason version of xport published to PyPI.

**Comment by selik** [comment]
Interesting. It looks like both spaces and all-zero bytes are acceptable padding. I'd say I'll look into it soon, but the truth is I'm too busy with other things at the moment. In the meantime, have you tried using Pandas' read_sas?

**Comment by selik** [comment]
@michelleb098 If you're comfortable editing the code, I think fixing this wouldn't be that bad. You could use an `or` to check for either spaces or `\x00`.

**Comment by selik** [comment]
Sorry it took so long to fix this. I believe I'm handling both kinds of padding now. #34
