### ISSUE TITLE
No module named 'xport.v56'; 'xport' is not a package

### ISSUE THREAD

**Issue by pressleydavid** [selik/xport#42]
I get this error when I attempt to do `import xport.v56`
I am using the Python standard library virtual environment created via `python -m venv .venv`, but I note that there may be a conda configuration requirement. Could this be what is causing my code to fail?

**Comment by selik** [comment]
@pressleydavid I personally use Conda to develop the module, but the standard library `venv` should be fine. You don't need a virtual environment at all, though it's recommended.

How did you install `xport`? I'm not a regular user of the standard library `venv` module, but I think the commands would go something like this:
```
python -m venv .venv
source .venv/bin/activate
python -m pip install xport
```

**Comment by pressleydavid** [comment]
Well, this is embarrassing... I created a file in my root workspace directory named... `xport.py` as my "main" file.  
As such, when I did `import xport`, I'm guessing it imported itself, and didn't search any further down the path, meaning `import xport.v56` would give the error referenced.

Sorry for the distraction. I realize this isn't the helpdesk, but certainly appreciate your confirmation that it wasn't a conda/venv configuration issue

**Comment by selik** [comment]
Don't be embarrassed. That's a common issue. There have been long discussions of how to provide a good error message or warning when someone accidentally shadows the module they're interested in. Unfortunately, there's no good way to distinguish accidental from intentional shadowing.

**Comment by selik** [comment]
@pressleydavid One habit I have: If I get a "module has no ..." error that surprises me, I check the module's `__file__` attribute to figure out where that file came from. Usually I discover it's the same mistake you had. You'd have seen it if you had checked `import xport; print(xport.__file__)`.
