### ISSUE TITLE
Treatment of `None` in character columns

### ISSUE THREAD

**Issue by selik** [selik/xport#44]
I'm trying to figure out if `None` in character columns should be written as empty string or some kind of sentinel value, like an ASCII NUL character.

**Comment by selik** [comment]
Reading SAS language documentation suggests that SAS does not support a distinction between the empty string `""` and `None` values. So, Python `None` should be encoded in XPT-format as a blank string.

**Comment by pressleydavid** [comment]
I think I have a similar issue around this as well... (I haven't updated the package yet, and not sure if your recent commits are packaged yet anyway?)
In any case, it seems like I am seeing something very similar in terms of values of "NULL" which exist in a CSV file I am trying to convert to XPT. I'll attach a screenshot, and try to explain:

1. Raw CSV values exist as either ('NULL', 'NOT DONE')
2. Non-printable placeholder characters are present when converting to XPT if 'NULL' values are present

It is puzzling that some values such as the combination of  'NULL' and 'NOT DONE BOOM' seem to reflect the intended behavior, even though 'NULL' is present in the cells which are not 'NOT DONE BOOM'. The value 'Z' in a cell with other values being 'NULL' also seems to work. 

Here are some screenshots. Happy to help with this, but may need some minimal hand-holding to start with, provided this is the same issue and still exists

![Screen Shot 2020-05-20 at 2 12 09 PM](https://user-images.githubusercontent.com/2701513/83075962-b4cf6d80-a042-11ea-995e-6526f19eff83.png)

<img width="225" alt="RawCSVValues" src="https://user-images.githubusercontent.com/2701513/83075991-c0229900-a042-11ea-9d71-679161afbf91.png">

**Comment by selik** [comment]
@pressleydavid Do you mind updating (`python -m pip install --upgrade xport`) and checking again? I changed the behavior recently. Previously, the module encoded Pandas' NA in a `'string'` series as `b'0x00'`, which is the unprintable ASCII NUL character. Now it encodes to `b' '` (space).

**Comment by selik** [comment]
@pressleydavid It looks like I can get a 30-day free trial of JMP. That'd let me test it out locally. If you update and it still misbehaves, I'll use JMP to debug. Right now I don't have any real SAS software to test against.

**Comment by pressleydavid** [comment]
Ok, I'll give you an update shortly.  University Edition SAS might be a better option over the hassle of requesting the license for a 30 day trial of JMP

**Comment by pressleydavid** [comment]
I have updated to xport 3.2.1, and can confirm that the csv source string 'NULL' still encodes to the unprintable ASCII nul 


<img width="182" alt="Screen Shot 2020-05-28 at 9 40 30 AM" src="https://user-images.githubusercontent.com/2701513/83150196-002c5f00-a0c9-11ea-91c2-6be1d52885ce.png">
<img width="138" alt="Screen Shot 2020-05-28 at 9 44 08 AM" src="https://user-images.githubusercontent.com/2701513/83150198-002c5f00-a0c9-11ea-8d0f-687e4926b5d5.png">
<img width="154" alt="Screen Shot 2020-05-28 at 9 44 52 AM" src="https://user-images.githubusercontent.com/2701513/83150200-002c5f00-a0c9-11ea-94e9-e08cad2d721f.png">

**Comment by pressleydavid** [comment]
I'm still experiencing this as an issue. Is it related to the #46 by chance?

**Comment by selik** [comment]
Darn. I added a [test](https://github.com/selik/xport/blob/04aca9360707a120c9ed410b4fe081b046c61375/test/test_v56.py#L333) for this issue which appears to pass.

What happens for you if you try this code in the REPL?
```
        df = pd.DataFrame({
            'a': pd.Series([None], dtype='string'),
            'b': [0],  # Avoid issue #46 by including a numeric column.
        })
        bytestring = xport.v56.dumps(df)
        library = xport.v56.loads(bytestring)
        assert list(next(iter(library.values()))['a']) == ['']
```

**Comment by pressleydavid** [comment]
I did not get an AssertionError with the REPL, perhaps the representation in JMP isn't that big of a deal. I never tested with SAS University either...

<img width="845" alt="Screen Shot 2020-07-19 at 2 41 27 PM" src="https://user-images.githubusercontent.com/2701513/87882458-1c17f700-c9ce-11ea-80c4-7a5d836a0acf.png">

**Comment by selik** [comment]
I tested Stata's behavior, and could not find a missing value distinct from empty string in a character column. I think this is resolved.
