### ISSUE TITLE
Write performance is much slower and a much larger result file is produced compared to pandas.to_csv()

### ISSUE THREAD

**Issue by dmoore247** [selik/xport#48]
Nice library and would like to use it, not sure how much work xport is doing, but finding it much slower than pandas .to_csv().
We're trying to process data outside of SAS, then move it back into SAS 9.4.6.

I have a Pandas DataFrame (10000000, 10) [All string objects]
`pdf.to_csv()` takes 30.46 seconds [670MB produced]
`xport.v56.dump(ds, f)` takes 6.12 minutes [3.5GB produced]

We're using pandas ==1.0.5 and underlying Pandas dataframe came from an Arrow type data structure.

I'm noticing that most of the time comes after the last `Converting column 'column10' from object to string`

I don't know what the results for a corresponding `.sas7bdat` file would be, but sas7bdat would be the real end goal.
Thanks!

**Comment by selik** [comment]
As for the speed, my guess is Pandas Cythonized `to_csv` whereas I haven't. I'm not entirely sure which function calls are the bottlenecks. It's a loop over an iterator and repeated calls to `struct.pack`.

The file size is entirely the fault of the archaic XPORT format. Every value in a character column must be padded to the same length as the largest value in that column. If all values are a single character, except for one which is 100 characters long, then every value written is padded to 100 characters. The CPORT format might fix this, but I haven't found a document describing it.

**Comment by selik** [comment]
@dmoore247 I suggest using CSV format. The XPT format is really only useful for sending data to external organizations that require it, like the FDA.

**Comment by selik** [comment]
I'm going to mark this as duplicate with #35 and/or #36.
