### ISSUE TITLE
 Sas Transort V8 character limit compatibility

### ISSUE THREAD

**Issue by biojerm** [selik/xport#53]
I followed this wonderful link from the docs that knew just what I wanted
```
If you want the relative comfort of SAS Transport v8’s limit of 246 characters, please make an enhancement request.
```

Is this upgrade feasible?

**Comment by selik** [comment]
Yeah, it shouldn't be too bad. I've just been lazy. Maybe I can blame it on the weather being too nice? :-)

**Comment by selik** [comment]
But, I must ask, why are you writing XPT files? Is there a particular organization that requires it? I've heard the FDA does.

**Comment by biojerm** [comment]
Yeah we have some partners that prefer the XPT format.  Unfortunately, I can't say who.

**Comment by selik** [comment]
No worries. I need to merge PR #51 first, so I'm not sure when I'll get to implementing v8/9. If you're interested in volunteering, I'd be happy to videochat and talk through how I plan to do it.

**Comment by biojerm** [comment]
Let me check in with my manager, to see if I can put some work hours on this.

**Comment by selik** [comment]
I'll ship this by the end of 2021. #10 #73
