### ISSUE TITLE
Support for SAS Version 8 Transport Files

### ISSUE THREAD

**Issue by bridgetmc** [selik/xport#60]
It would be great if support could be added for SAS Version 8. Thanks for this great library.

**Comment by selik** [comment]
@bridgetmc You're welcome. I wish I had more time to maintain it! One of these days I'll have to take a little vacation to tend to it.

**Comment by zhangwx2020** [comment]
I would also like to see SAS XPT V8 support. 
Thanks,
Bill

**Comment by selik** [comment]
@bridgetmc @zhangwx2020 Are you mostly interested in reading XPT files or also writing them?

**Comment by zhangwx2020** [comment]
> @bridgetmc @zhangwx2020 Are you mostly interested in reading XPT files or also writing them?
We are interested in writing XPT from csv/excel files.
Thanks,
Bill

**Comment by selik** [comment]
@zhangwx2020 @bridgetmc I'll ship this feature by the end of 2021. #10 #73
