### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2076' in position 2: ordinal not in range(256)

### ISSUE THREAD

**Issue by kennest** [selik/xport#67]
I've superscript chars in some rows and while i attempted to generate XPT il show this error.
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2076' in position 2: ordinal not in range(256)
please helps

**Comment by selik** [comment]
It sounds like those superscript characters aren't supported by the XPT format. Replace them with a different character.
