### ISSUE TITLE
SAS metadata Length

### ISSUE THREAD

**Issue by kennest** [selik/xport#68]
Please anyone know how to set the Length metadata on a column :
`for k, v in ds.items():
    for i,n in sdtm_specs.iterrows():
        if k == n['Variable Name']:
            v.label=n['Label']
            v.length=n['Length']
            if v.dtype == 'object':
                v.format = '$CHAR20.'
            else:
                v.format = '10.2'
`

**Comment by selik** [comment]
Isn't the `$CHAR20.` setting the length to 20?

**Comment by kennest** [comment]
> Isn't the `$CHAR20.` format setting the length to 20? What do you mean by the length?

I made a mistake, to set the length we need to use v.width instead of v.length.
Thx
