### ISSUE TITLE
Just because you do not understand something it does not mean it is "archaic".

### ISSUE THREAD

**Issue by entropy1177** [selik/xport#91]
.XPT files are impossible to work with because they are made to transfer protected health information. Not everybody wants their PHI Open Source.

**Comment by selik** [comment]
SAS published the [SAS Transport (XPT, XPORT) File Format](https://www.loc.gov/preservation/digital/formats/fdd/fdd000464.shtml) standard. It's openly/publicly available to read the details. This file format does not encrypt or protect information, nor was it made for health information specifically.

Happily, the file format isn't "impossible" to work with, as this project demonstrates.

**Comment by selik** [comment]
As for whether it's archaic, that depends on your sense of time. [IBM's hexadecimal floating-point](https://en.wikipedia.org/wiki/IBM_hexadecimal_floating-point) standard seems almost prehistoric to me. If you think in terms of the [UNIX Epoch](https://en.wikipedia.org/wiki/Unix_time), it was invented before time zero. In a sense, that's before the beginning of time.
